"""empty message

Revision ID: 306c7581d0ca
Revises: 823b892f4e67
Create Date: 2022-05-27 19:40:08.663904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306c7581d0ca'
down_revision = '823b892f4e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_news_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_news')
    )
    # ### end Alembic commands ###
