"""empty message

Revision ID: 5d65a51caf31
Revises: cb1500871073
Create Date: 2022-05-25 23:08:37.215270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d65a51caf31'
down_revision = 'cb1500871073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_answer_category_name_category', type_='foreignkey')
        batch_op.drop_column('category_name')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_category_name_category', type_='foreignkey')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key('fk_question_category_name_category', 'category', ['category_name'], ['name'], ondelete='CASCADE')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key('fk_answer_category_name_category', 'category', ['category_name'], ['name'], ondelete='CASCADE')

    # ### end Alembic commands ###
