"""empty message

Revision ID: 792ed3b027f5
Revises: 966e9baaf2cb
Create Date: 2022-05-26 00:28:13.394591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792ed3b027f5'
down_revision = '966e9baaf2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('free_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['free_id'], ['free.id'], name=op.f('fk_free_voter_free_id_free'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_free_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'free_id', name=op.f('pk_free_voter'))
    )
    op.create_table('fanswer_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fanswer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fanswer_id'], ['fanswer.id'], name=op.f('fk_fanswer_voter_fanswer_id_fanswer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_fanswer_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'fanswer_id', name=op.f('pk_fanswer_voter'))
    )
    with op.batch_alter_table('fanswer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fanswer_question_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_fanswer_question_id_free'), 'free', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fanswer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fanswer_question_id_free'), type_='foreignkey')
        batch_op.create_foreign_key('fk_fanswer_question_id_question', 'question', ['question_id'], ['id'], ondelete='CASCADE')

    op.drop_table('fanswer_voter')
    op.drop_table('free_voter')
    # ### end Alembic commands ###
