"""empty message

Revision ID: 90289f962663
Revises: df809847e181
Create Date: 2022-05-27 19:27:06.563590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90289f962663'
down_revision = 'df809847e181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('fk_news_user_id_user', type_='foreignkey')
        batch_op.drop_column('modify_date')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('news_voter', schema=None) as batch_op:
        batch_op.drop_constraint('fk_news_voter_news_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_news_voter_news_id_news'), 'news', ['news_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_news_voter_news_id_news'), type_='foreignkey')
        batch_op.create_foreign_key('fk_news_voter_news_id_question', 'question', ['news_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('modify_date', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key('fk_news_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
