"""empty message

Revision ID: cb1500871073
Revises: e7fba4798913
Create Date: 2022-05-23 14:11:21.065225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1500871073'
down_revision = 'e7fba4798913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_answer_category_name_category'), 'category', ['category_name'], ['name'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_category_name_category'), type_='foreignkey')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
