"""empty message

Revision ID: d334a3934cd4
Revises: 90289f962663
Create Date: 2022-05-27 19:32:19.013709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd334a3934cd4'
down_revision = '90289f962663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_voter', schema=None) as batch_op:
        batch_op.drop_constraint('fk_news_voter_news_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_news_voter_news_id_news'), 'news', ['news_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_voter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_news_voter_news_id_news'), type_='foreignkey')
        batch_op.create_foreign_key('fk_news_voter_news_id_question', 'question', ['news_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
