"""empty message

Revision ID: df809847e181
Revises: b2764d89dd69
Create Date: 2022-05-27 18:00:34.758989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df809847e181'
down_revision = 'b2764d89dd69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['question.id'], name=op.f('fk_news_voter_news_id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_news_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'news_id', name=op.f('pk_news_voter'))
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_news_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_news_user_id_user'), type_='foreignkey')
        batch_op.drop_column('modify_date')
        batch_op.drop_column('user_id')

    op.drop_table('news_voter')
    # ### end Alembic commands ###
